import React from 'react';

export const allItemsData = [
  {
    id: '1',
    type: 'book',
    title: 'React para Iniciantes',
    img: 'https://placehold.co/200x300/7c3aed/white?text=React',
    details: {
      author: 'João Silva',
      pages: 250,
      description:
        'Um guia completo para começar com React. Cobre hooks, context API e mais.',
      genres: ['Programação', 'Web'],
      averageRating: 4.5,
      ratingsCount: 125,
      year: 2022,
      publisher: 'Tech Books',
      availability: { onlineStoreUrl: '#', libraryUrl: '#', downloadUrl: null },
      similarBooks: ['3', '6'],
    },
    popular: true,
    recentReview: {
      userId: 'user2',
      user: 'Ana',
      rating: 5,
      text: 'Muito didático!',
    },
  },
  {
    id: '2',
    type: 'book',
    title: 'Minha vida como calvo',
    img: 'https://media.istockphoto.com/id/1147544809/vector/no-thumbnail-image-vector-graphic.jpg?s=170667a&w=0&k=20&c=v9QBkaN6fXxy1b-wsTQ6QhHUVGLo8JMMxhUBcWzOH0A=',
    details: {
      author: 'João Luiz',
      pages: 10,
      description:
        'Como ser um calvo de sucesso',
      genres: ['Vida', 'Dicas'],
      averageRating: 5.0,
      ratingsCount: 500,
      year: 2025,
      publisher: 'Calvones',
      availability: { onlineStoreUrl: '#', libraryUrl: '#', downloadUrl: null },
      similarBooks: [],
    },
    popular: true,
    recentReview: {
      userId: 'user2',
      user: 'Luiz',
      rating: 5,
      text: 'Ja estou utilizando as dicas',
    },
  },
  {
    id: '3',
    type: 'book',
    title: 'game design red dead redemption',
    img: 'https://media.istockphoto.com/id/1147544809/vector/no-thumbnail-image-vector-graphic.jpg?s=170667a&w=0&k=20&c=v9QBkaN6fXxy1b-wsTQ6QhHUVGLo8JMMxhUBcWzOH0A=',
    details: {
      author: 'Caio Braga',
      pages: 200,
      description:
        'Como eu fiz meu jogo de sucesso',
      genres: ['Jogo', 'Game Design'],
      averageRating: 5.0,
      ratingsCount: 500,
      year: 2025,
      publisher: 'Calvones',
      availability: { onlineStoreUrl: '#', libraryUrl: '#', downloadUrl: null },
      similarBooks: [],
    },
    popular: true,
    recentReview: {
      userId: 'user2',
      user: 'Luiz',
      rating: 5,
      text: 'Ja estou utilizando as dicas',
    },
  },
  {
    id: '4',
    type: 'book',
    title: 'React para Seniors',
    img: 'https://placehold.co/200x300/7c3aed/white?text=React',
    details: {
      author: 'João Silva',
      pages: 350,
      description:
        'Um guia completo para Seniors.',
      genres: ['Programação', 'Web'],
      averageRating: 5.0,
      ratingsCount: 110,
      year: 2024,
      publisher: 'Tech Books',
      availability: { onlineStoreUrl: '#', libraryUrl: '#', downloadUrl: null },
      similarBooks: ['3', '6', '1'],
    },
    popular: true,
    recentReview: {
      userId: 'user2',
      user: 'Ana',
      rating: 5,
      text: 'Muito didático!',
    },
  },
  {
    id: '5',
    type: 'book',
    title: 'Styled Components Essencial',
    img: 'https://placehold.co/200x300/16a34a/white?text=Styled',
    details: {
      author: 'Maria Souza',
      pages: 180,
      description: 'Domine a estilização CSS-in-JS com exemplos práticos.',
      genres: ['Programação', 'CSS'],
      averageRating: 4.2,
      ratingsCount: 98,
      year: 2021,
      publisher: 'Web Style',
      availability: { onlineStoreUrl: '#', libraryUrl: '#', downloadUrl: '#' },
      similarBooks: ['1', '6'],
    },
    popular: true,
    recentReview: {
      userId: 'user3',
      user: 'Carlos',
      rating: 4,
      text: 'Gostei, mas faltou exemplos avançados.',
    },
  },
  {
    id: '6',
    type: 'book',
    title: 'JavaScript Moderno',
    img: 'https://placehold.co/200x300/f97316/white?text=JS',
    details: {
      author: 'Carlos Pereira',
      pages: 400,
      description:
        'Guia completo de ES6+ e funcionalidades recentes do JavaScript.',
      genres: ['Programação', 'Web'],
      averageRating: 4.6,
      ratingsCount: 215,
      year: 2023,
      publisher: 'Code Masters',
      availability: { onlineStoreUrl: '#', libraryUrl: null, downloadUrl: '#' },
      similarBooks: ['1', '3'],
    },
    popular: true,
    recentReview: null,
  },
];

// --- Dados de Usuários (Simulado) ---
export const allUsersData = [
  {
    id: 'user1',
    username: 'Leitor Detalhista',
    email: 'leitorDeta@gmail.com',
    born_in: '15/04/2000',
    gender: 'Masculino',
    avatar: 'https://placehold.co/40x40/8b5cf6/ffffff?text=L',
    bio: 'Explorando mundos...',
    followers: ['user2'],
    following: ['user3', 'user5'],
    book_read: [],
  },
  {
    id: 'user2',
    username: 'Ana',
    email: 'ana@gmail.com',
    born_in: '20/09/2006',
    gender: 'Feminino',
    avatar: 'https://placehold.co/40x40/ec4899/ffffff?text=A',
    bio: 'Amante de livros de React.',
    followers: [],
    following: ['user1'],
  },
  {
    id: 'user3',
    username: 'Carlos',
    email: 'carlos@gmail.com',
    born_in: '01/01/1990',
    gender: 'Masculino',
    avatar: 'https://placehold.co/40x40/10b981/ffffff?text=C',
    bio: 'CSS-in-JS é vida!',
    followers: ['user1'],
    following: [],
  },
  {
    id: 'user4',
    username: 'GamerX',
    email: 'gamerX@gmail.com',
    born_in: '29/12/2004',
    gender: 'Feminino',
    avatar: 'https://placehold.co/40x40/f59e0b/ffffff?text=G',
    bio: 'Zerando tudo.',
    followers: [],
    following: [],
  },
  {
    id: 'user5',
    username: 'Cinefilo',
    email: 'lgbt@gmail.com',
    born_in: '01/01/2023',
    gender: 'Não Binario',
    avatar: 'https://placehold.co/40x40/3b82f6/ffffff?text=C',
    bio: 'Cinema é arte.',
    followers: ['user1'],
    following: [],
  },
  {
    id: 'user6',
    username: 'Caio',
    email: 'caio@gmail.com',
    born_in: '03/09/2002',
    gender: 'Masculino',
    avatar: 'https://placehold.co/40x40/ef4444/ffffff?text=D',
    bio: 'Lendo Duna',
    followers: [],
    following: ['user1', 'user3'],
  },
];

export const popularReviewsData = [];

export const recentReviews = [];

export const reviews = [
  {
    reviewId: '300023',
    userId: 'user2',
    user: 'Ana',
    rating: 5,
    text: 'Muito didático!',
    review_likes: 5,
    review_data: '2025-04-05',
  },
];
